# Change these first
owner: inwage # Your GitHub organization or username, where this repository lives
repo: status_page # The name of this repository

sites:
  - name: proxy api production
    url: https://proxy.bitwage.com
  - name: proxy api sandbox
    url: https://proxy1.bitwage.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status_page
  logoUrl: https://bitwage-images.s3.amazonaws.com/bitwage_status.png
  name: Bitwage v2 Status Page
  introTitle: "Bitwage v2 Status Page"
  introMessage: Bitwage v2 Status Page
  navbar:
    - title: Status
      href: /
    - title: Bitwage
      href: https://www.bitwage.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
