# Change these first
owner: inwage # Your GitHub organization or username, where this repository lives
repo: status_page # The name of this repository

sites:
  - name: Bitwage Homepage
    url: https://www.bitwage.com
  - name: Bitwage Support
    url: https://support.bitwage.com
  - name: Bitwage Blog
    url: https://blog.bitwage.com

#  - name: proxy api production
#    url: $PROXY_PROD_URL1
#  - name: proxy api sandbox
#    url: $PROXY_SANDBOX_URL1
#  - name: proxy api documentation
#    url: $PROXY_DOCS_URL
#    headers:
#      - "Authorization: Basic $PROXY_DOCS_BASIC_AUTH"
#
  - name: Bitwage API
    url: https://api2.bitwage.com
  - name: Bitwage API (Sandbox)
    url: https://api.sandbox.bitwage.com
  - name: Bitwage API Docs
    url: https://developer.bitwage.com
#
#  - name: user portal frontend sandbox
#    url: https://app.sandbox.bitwage.com
#  - name: user portal frontend production
#    url: https://app.bitwage.com
#
#  - name: admin portal frontend sandbox
#    url: $ADMIN_FRONTEND_SANDBOX_URL
#  - name: admin portal frontend production
#    url: $FRONTEND_ADMIN_PROD_URL

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bitwage.com
  #baseUrl: /status_page
  logoUrl: https://bitwage-images.s3.amazonaws.com/bitwage_status_lg2.png
  name: Bitwage Status Page
  introTitle: "Bitwage Status Page"
  introMessage: Bitwage Status Page
  navbar:
    - title: Status
      href: /
    - title: Bitwage
      href: https://www.bitwage.com
  favicon: https://bitwage-images.s3.amazonaws.com/favicon.ico
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
