# Change these first
owner: inwage # Your GitHub organization or username, where this repository lives
repo: status_page # The name of this repository

sites:
  - name: pay api production
    url: $PAY_PORTAL_PROD_URL
  - name: pay api sandbox
    url: $PAY_PORTAL_SANDBOX_URL
  - name: pay api documentation
    url: $PAY_PORTAL_DOCS_URL
    headers:
      - "Authorization: Basic $PAY_PORTAL_DOCS_BASIC_AUTH"
      
  - name: proxy api production
    url: $PROXY_PROD_URL1
  - name: proxy api sandbox
    url: $PROXY_SANDBOX_URL1
  - name: proxy api documentation
    url: $PROXY_DOCS_URL
    headers:
      - "Authorization: Basic $PROXY_DOCS_BASIC_AUTH"
      
  - name: bitwage api sandbox
    url: https://api.sandbox.bitwage.com
  - name: bitwage api production
    url: https://api2.bitwage.com
  - name: private bitwage api documentation
    url: $BITWAGE_API_DOCS_URL
    headers:
      - "Authorization: Basic $BITWAGE_API_DOCS_BASIC_AUTH"
  - name: public bitwage api documentation
    url: https://docs1.bitwage.com
    
  - name: user portal frontend sandbox
    url: https://app.sandbox.bitwage.com
  - name: user portal frontend production
    url: https://app.bitwage.com
    
  - name: admin portal frontend sandbox
    url: $ADMIN_FRONTEND_SANDBOX_URL
  - name: admin portal frontend production
    url: $FRONTEND_ADMIN_PROD_URL

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status2.bitwage.com
  #baseUrl: /status_page
  logoUrl: https://bitwage-images.s3.amazonaws.com/bitwage_status.png
  name: Bitwage v2 Status Page
  introTitle: "Bitwage v2 Status Page"
  introMessage: Bitwage v2 Status Page
  navbar:
    - title: Status
      href: /
    - title: Bitwage
      href: https://www.bitwage.com
  favicon: https://bitwage-images.s3.amazonaws.com/favicon.ico
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
